### PR TITLE
Update linked libraries for LLVM 4.0

### PR DESCRIPTION
**Pull request by segiddins**

### CODE REVIEW

**Comment by segiddins** [comment]
I wanted to get this running on CI, hope thats ok @harlanhaskins

**Comment by harlanhaskins** [comment]
Of course! Is the LLVM 4.0 bottle merged in?

**Comment by segiddins** [comment]
When I `brew reinstall llvm` locally it installed 4.0 ¯\_(ツ)_/¯

**Comment by harlanhaskins** [comment]
Works for me. Let's let CI test this.

**Comment by harlanhaskins** [comment]
🚢 :it:

**Pull request merged**
