### PR TITLE
Remove GC & build the runtime with swiftpm

### PR DESCRIPTION
**Pull request by segiddins**

### CODE REVIEW

**Review by harlanhaskins — CHANGES_REQUESTED** [review]
Looks good -- we should I guess say that trill is gonna leak like crazy until we add ARC...

Also, I don't think we should rename `runtime` to `trillRuntime`. You can set a custom source dir in the package manifest.

**Comment by harlanhaskins** [comment]
Also the build script needs to be updated to move the runtime from the new SwiftPM-devised destination.

**Comment by segiddins** [comment]
> Also the build script needs to be updated to move the runtime from the new SwiftPM-devised destination.

I think I've already done that?

**Comment by harlanhaskins** [comment]
> `IOError: [Errno 2] No such file or directory: '/Users/distiller/trill/.build/Debug/lib/libtrillRuntime.a'`

**Comment by segiddins** [comment]
> Also, I don't think we should rename runtime to trillRuntime. You can set a custom source dir in the package manifest.

but that would conflict with the existing `Runtime` directory

**Comment by segiddins** [comment]
> Looks good -- we should I guess say that trill is gonna leak like crazy until we add ARC...

We could also just write a mark/sweep GC in the meantime :P

**Comment by segiddins** [comment]
@harlanhaskins I think I did what you wanted w/r/t the location of the runtime?

**Review by harlanhaskins — APPROVED** [review]

**Comment by harlanhaskins** [comment]
Looks great!

**Comment by segiddins** [comment]
Merging, despite the random CI failures.

**Pull request merged**
