### PR TITLE
[ClangImporter] Allow importing func decl overloads

### LINKED ISSUE #28: Allow overloading imported functions.
Something is preventing

```swift
func putchar(_ char: Int8) {
  putchar(char as Int32)
}
```

from compiling.

### PR DESCRIPTION
**Pull request by segiddins**
Closes #28

### CODE REVIEW

**Review by harlanhaskins — APPROVED** [review]
Thanks!

**Comment by harlanhaskins** [comment]
Oh, hey, so this actually fixes some issues in the tests themselves.

**Comment by segiddins** [comment]
Travis is 🍏

**Comment by harlanhaskins** [comment]
Woo!

**Pull request merged**
